// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package core

var TableNames = struct {
	MediaUploads                    string
	OutgoingEmails                  string
	PostComments                    string
	PostStats                       string
	Posts                           string
	SystemSettings                  string
	UserAPIKeys                     string
	UserConnectionMediationRequests string
	UserConnectionMediators         string
	UserConnections                 string
	UserInvitations                 string
	UserSignupRequests              string
	Users                           string
	WhitelistedConnections          string
}{
	MediaUploads:                    "media_uploads",
	OutgoingEmails:                  "outgoing_emails",
	PostComments:                    "post_comments",
	PostStats:                       "post_stats",
	Posts:                           "posts",
	SystemSettings:                  "system_settings",
	UserAPIKeys:                     "user_api_keys",
	UserConnectionMediationRequests: "user_connection_mediation_requests",
	UserConnectionMediators:         "user_connection_mediators",
	UserConnections:                 "user_connections",
	UserInvitations:                 "user_invitations",
	UserSignupRequests:              "user_signup_requests",
	Users:                           "users",
	WhitelistedConnections:          "whitelisted_connections",
}
