// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package core

var TableNames = struct {
	Posts                  string
	SystemSettings         string
	UserConnections        string
	UserInvitations        string
	UserSignupRequests     string
	Users                  string
	WhitelistedConnections string
}{
	Posts:                  "posts",
	SystemSettings:         "system_settings",
	UserConnections:        "user_connections",
	UserInvitations:        "user_invitations",
	UserSignupRequests:     "user_signup_requests",
	Users:                  "users",
	WhitelistedConnections: "whitelisted_connections",
}
