// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package core

var TableNames = struct {
	LoginAttempts                   string
	MediaUploads                    string
	NormalizedUrls                  string
	OutgoingEmails                  string
	PostComments                    string
	PostPrompts                     string
	PostShares                      string
	PostStats                       string
	Posts                           string
	RSSFeeds                        string
	RSSItems                        string
	SystemSettings                  string
	TranslationJobs                 string
	TranslationUsage                string
	Translations                    string
	UserAPIKeys                     string
	UserConnectionMediationRequests string
	UserConnectionMediators         string
	UserConnections                 string
	UserFeedItems                   string
	UserFeedSubscriptions           string
	UserFeedTokens                  string
	UserInvitations                 string
	UserProfiles                    string
	UserSignupRequests              string
	UserStyles                      string
	UserTranslationLanguages        string
	Users                           string
	WhitelistedConnections          string
}{
	LoginAttempts:                   "login_attempts",
	MediaUploads:                    "media_uploads",
	NormalizedUrls:                  "normalized_urls",
	OutgoingEmails:                  "outgoing_emails",
	PostComments:                    "post_comments",
	PostPrompts:                     "post_prompts",
	PostShares:                      "post_shares",
	PostStats:                       "post_stats",
	Posts:                           "posts",
	RSSFeeds:                        "rss_feeds",
	RSSItems:                        "rss_items",
	SystemSettings:                  "system_settings",
	TranslationJobs:                 "translation_jobs",
	TranslationUsage:                "translation_usage",
	Translations:                    "translations",
	UserAPIKeys:                     "user_api_keys",
	UserConnectionMediationRequests: "user_connection_mediation_requests",
	UserConnectionMediators:         "user_connection_mediators",
	UserConnections:                 "user_connections",
	UserFeedItems:                   "user_feed_items",
	UserFeedSubscriptions:           "user_feed_subscriptions",
	UserFeedTokens:                  "user_feed_tokens",
	UserInvitations:                 "user_invitations",
	UserProfiles:                    "user_profiles",
	UserSignupRequests:              "user_signup_requests",
	UserStyles:                      "user_styles",
	UserTranslationLanguages:        "user_translation_languages",
	Users:                           "users",
	WhitelistedConnections:          "whitelisted_connections",
}
